[workspace]
members = [ "rowan", "rowan_shared","rowanc", "rowan-runtime", "rowan-unwind"]
resolver = "2"

[workspace.dependencies]
rowan_shared = { path = "rowan_shared" }
rowan-unwind = { path = "rowan-unwind" }
rowan-runtime = { path = "rowan-runtime" }
