[package]
name = "rowan"
version = "0.1.0"
edition = "2021"

[dependencies]
rowan_shared = { workspace = true }
cranelift = "0.118.0"
cranelift-module = "0.118.0"
cranelift-jit = { version = "0.118.0", features = ["selinux-fix"] }
cranelift-native = "0.118.0"
crossbeam-deque = "0.8.6"
