[package]
name = "rowanc"
version = "0.1.0"
edition = "2021"

[dependencies]
lalrpop-util = "0.22.0"
ariadne = "0.5.0"
either = "1.13.0"
rowan_shared = { workspace = true }

[build-dependencies]
lalrpop = "0.22.0"
